# Generated by Django 4.0.3 on 2022-06-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0003_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='createdon',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
